#!/usr/bin/env python3
"""
Writes projects/<id>/state/SUMMARY.md - a compact, human/LLM-readable digest
of a project's current state, regenerated on demand (not auto-triggered by
other scripts, since it's cheap and its whole point is to be re-run
deliberately at the end of a work block).

Purpose: this session repeatedly re-derived "where is this project right
now" by reading project.json, every scenes/*.json, and several state/*
files from scratch. A single short summary file - phase, last N decisions,
asset counts, known open findings - lets a future session (or a future
turn in a long one) resume without that re-derivation cost. This does NOT
replace decisions_log (which carries full reasoning, never truncated) or
any state/*.json (which stay the source of truth) - SUMMARY.md is a
snapshot, cheap to regenerate, safe to ignore if stale (it says so).

Usage:
    python3 scripts/generate_project_summary.py <PRJ-id>
    python3 scripts/generate_project_summary.py --all
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
PROJECTS_DIR = REPO_ROOT / "projects"


def count_globs(base: Path, *patterns: str) -> dict[str, int]:
    return {pat: len(list(base.glob(pat))) for pat in patterns if (base / "").exists()}


def latest_decisions(project: dict, n: int = 3) -> list[dict]:
    return project.get("decisions_log", [])[-n:]


def open_findings(state_dir: Path) -> list[str]:
    """Best-effort scan of state/*.json for anything that looks like an
    unresolved finding - conservative (string match on known keys), never
    claims completeness."""
    findings = []
    for f in sorted(state_dir.glob("*.json")):
        try:
            d = json.loads(f.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        if isinstance(d, dict):
            for key in ("conclusion", "recommendation"):
                if key in d and isinstance(d[key], str) and d[key].strip():
                    findings.append(f"{f.name}: {d[key][:200]}")
    return findings


def summarize(project_id: str) -> None:
    project_dir = PROJECTS_DIR / project_id
    project_json = project_dir / "project.json"
    if not project_json.exists():
        print(f"{project_id}: SKIP (no project.json)")
        return

    project = json.loads(project_json.read_text())
    state_dir = project_dir / "state"
    scenes_dir = project_dir / "scenes"
    assets_dir = project_dir / "assets"

    scene_count = len(list(scenes_dir.glob("SC-*.json"))) if scenes_dir.exists() else 0
    still_count = len(list((assets_dir / "still").glob("*"))) if (assets_dir / "still").exists() else 0
    video_count = len(list((assets_dir / "video").glob("*"))) if (assets_dir / "video").exists() else 0
    audio_count = len(list((assets_dir / "audio").glob("*.wav"))) if (assets_dir / "audio").exists() else 0

    lines = [
        f"# {project.get('title', project_id)}",
        "",
        f"_Auto-generated by scripts/generate_project_summary.py at "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} - a snapshot, "
        f"may be stale. Source of truth is always project.json/scenes/state/, never this file._",
        "",
        f"**project_id:** `{project_id}`  ",
        f"**production_phase:** `{project.get('production_phase', 'unset')}`  ",
        f"**template_ref:** `{project.get('template_ref', '—')}`  ",
        f"**style_profile_ref:** `{project.get('style_profile_ref', '—')}`",
        "",
        "## Counts",
        f"- Scenes: {scene_count}",
        f"- Stills: {still_count}  ·  Videos: {video_count}  ·  Narration WAVs: {audio_count}",
    ]

    img_target = project.get("image_count_target")
    vid_target = project.get("video_count_target")
    if img_target is not None:
        lines.append(f"- Target: {img_target} images, {vid_target} videos")

    decisions = latest_decisions(project)
    if decisions:
        lines += ["", "## Last decisions"]
        for d in decisions:
            lines.append(f"- **{d.get('date', '?')}**: {d.get('decision', '')[:220]}")

    if state_dir.exists():
        findings = open_findings(state_dir)
        if findings:
            lines += ["", "## Findings worth re-reading (state/*.json conclusion/recommendation fields)"]
            for f in findings[:10]:
                lines.append(f"- {f}")

    out_path = state_dir / "SUMMARY.md"
    state_dir.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"{project_id}: wrote {out_path.relative_to(REPO_ROOT)}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    if sys.argv[1] == "--all":
        for p in sorted(PROJECTS_DIR.iterdir()):
            if p.is_dir() and p.name.startswith("PRJ-"):
                summarize(p.name)
    else:
        summarize(sys.argv[1])


if __name__ == "__main__":
    main()
